### ISSUE TITLE
Does not affect empty backgrounds

### ISSUE THREAD

**Issue by BHSPitMonkey** [Max-Github/FireFoxInvertColors#1]
See two examples:
- http://videlalvaro.github.io/2015/12/learning-about-distributed-systems.html (this site is mainly a white background, which does not get inverted)
- https://news.ycombinator.com/news (the white background behind the main content div is not inverted)

And others. The CSS seems like it should work. Maybe this is a bug in Firefox when using `filter` on the `html` element?

**Comment by Max-Github** [comment]
I am aware of this issue, but I am not really sure of the reason why it is not being applied all the time. I hope to have some time this weekend to look at it a bit more closely.

**Comment by Max-Github** [comment]
This has been partially fixed. The problem was that some websites did not define a background and text color, which resulted in no color being inverted. 

This fix resolved the issue on most of the problematic pages.

As for the rest, I think a possible solution might to be write some JS that would check if an element has a defined or inherited color, if not then a default would be applied.
