### ISSUE TITLE
Doesn't invert background if not explicitly defined?

### ISSUE THREAD

**Issue by cmeeren** [Max-Github/FireFoxInvertColors#7]
Try to invert colors on this page: https://developer.xamarin.com/guides/cross-platform/fsharp/samples/

As you can see, it inverts the main column (which has an explicitly defined background color of "white"), but not the main background (which has no explicitly defined background color, and thus defaults to white).

Otherwise, thanks for a nice plugin! Too bad it doesn't play nice with font smoothing (e.g. the font on [this page](https://www.relativisticramblings.com/ramblings/linux-im-giving-up-again/) looks much less clear when inverted; it looks fine when inverting the whole screen using the Windows built-in Magnifier tool), but I guess there's little you can do about that.

**Comment by Max-Github** [comment]
This plugin works by apply the following CSS:
https://github.com/Max-Github/FireFoxInvertColors/blob/master/style.css

The issue is that there is not much consistency between websites, and the above rule seems to work OK for most sites.

And at this point to simplicity, I would like to avoid having custom rules on a per site basis, as it would be nightmare to keep up to date, and users will still not be happy about it.

You can try using the following plugin to set custom CSS rules on websites:
https://addons.mozilla.org/en-US/firefox/addon/stylish/
